spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:49163/banking-connector-db
    username: banking-connector
    password: local-dev
  liquibase:
    change-log: classpath:database/changelog/changelog-master.yaml
    url: jdbc:postgresql://localhost:49163/banking-connector-db
    user: banking-connector
    password: local-dev
  rabbitmq:
    host: localhost
    port: 49166
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        transactionAdded-out-0:
          content-type: application/json
          destination: local.balancer_core.transaction_events
        transactionModified-out-0:
          content-type: application/json
          destination: local.balancer_core.transaction_events
        transactionRemoved-out-0:
          content-type: application/json
          destination: local.balancer_core.transaction_events
      rabbit:
        default:
          producer:
            bindQueue: false
            declareExchange: false
        bindings:
          transactionAdded-out-0:
            producer:
              routingKeyExpression: '''balancer_core.transaction_added'''
          transactionModified-out-0:
            producer:
              routingKeyExpression: '''balancer_core.transaction_modified'''
          transactionRemoved-out-0:
            producer:
              routingKeyExpression: '''balancer_core.transaction_removed'''

server:
  port: 49162

plaid:
  base-url: https://sandbox.plaid.com
  transactions-url: https://sandbox.plaid.com
  client-id: plaid-client-id
  secret: plaid-secret

rest-server:
  cors:
    allowed-origins: http://localhost:3000
