spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/banking-connector-db
    username: banking-connector
    password: local-dev

plaid:
  base-url: https://sandbox.plaid.com
  client-id: plaid-client-id
  secret: plaid-secret

rest-server:
  cors:
    allowed-origins: http://localhost:3000
